# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [125]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [126]:
A = np.arange(1, 16).reshape(3,5)

In [127]:
print(f'Number of axes för matrix A: {A.ndim}')
print(f'The shape of matrix A: {A.shape}')
print(f'The size of matrix A: {A.size}')
print(f'The datatype of matrix A: {A.dtype}')

Number of axes för matrix A: 2
The shape of matrix A: (3, 5)
The size of matrix A: 15
The datatype of matrix A: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [128]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [129]:
# Elementwise subtraction.
print(B - C)
print()
# Elementwise multiplication.
print(B * C)
print()
# Matrix multiplication.
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [130]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [131]:
# Exponentiate each number elementwise.
result = np.exp(B)
print(result)
print()
# Calculate the minimum value in the whole matrix.
print(B.min())
print()
# Calculcate the minimum value in each row.
print(B.min(axis=1))
print()
# Calculcate the minimum value in each column.
print(B.min(axis=0))
print()
# Find the index value for the minimum value in the whole matrix.
print(np.argmin(B))
print()
# Find the index value for the minimum value in each row.
print(np.argmin(B, axis=1))
print()
# Calculate the sum for all elements.
print(B.sum())
print()
# Calculate the mean for each column. 
print(B.mean(axis=0))
print()
# Calculate the median for each column. 
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [132]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [133]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [134]:
# The missing indices are considered complete slices
# A[1] => A[1, : ]
# Every kolumn for second row (entire row).

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [135]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [136]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [137]:
# By using the flat attribute.
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [138]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [139]:
# First an 1D array is created with 30 numbers (0-29) and is set to = a.
# Then b is set, reshaped from a, with new dimensions for a 3-dimensional array with (2, 3, -1)
# (2, 3, -1) meaning:
# The outermost (1st) dimension will have 2 elements/arrays which each will contain 3 elements/arrays (2nd dimension). 
# -1 = Numpy will automatically set the size/columns of the 3rd dimension based on the the other dimensions and total number of elements. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [140]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [141]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [142]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [143]:
def add_mult_matrices(arg1, arg2, operation):

    # Validate that the input are of the type numpy.ndarray
    if not isinstance(arg1, np.ndarray) or not isinstance(arg2, np.ndarray):
        return 'Both matrices must be arrays.'
        
    # Validate operation
    if operation != 'add' and operation != 'multiply':
        return 'Operation must be "add" or "multiply".'
        
    # Validate same sizes for addition
    if operation == 'add' and arg1.shape != arg2.shape:
        return 'The arrays must have the same sizes for addition.'
           
    # Validate that sizes conform when multiplication
    if operation == 'multiply' and arg1.shape[1] != arg2.shape[0]:
        return 'Number of columns in the first matrix must be equal to the number of rows in the second matrix.'

    if operation == 'add':
        result = arg1 + arg2
    else:
        result = arg1 @ arg2
        
    return result

# Verifying
arg1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arg2 = np.array([[1, 2],[3, 4],[5, 6]])
verify = add_mult_matrices(arg1, arg2, 'nisse')
verify2 = add_mult_matrices(arg1, arg2, 'add')
verify3 = add_mult_matrices(arg1, arg2, 'multiply')
print(verify)
print(verify2)
print(verify3)


Operation must be "add" or "multiply".
The arrays must have the same sizes for addition.
[[ 22  28]
 [ 49  64]
 [ 76 100]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [144]:
# 10.1.1    x = (4, 3)
x = np.array([[4, 3]])
print(f'a)    Shape:{x.shape}  => dimension 1 x 2 (a row vector with 2 elements)')
print(f'b)    {5*x}')
print(f'c)    {3*x}')
print(f'd)    {5*x +3*x}')
print(f'e)    {8*x}')
print(f'f)    {4*x - x}')
print(f"g)    Since transposing a 1D row vector doesn't make any differense in Numpy I've chosen to write the array as an 2D array") 
print(f'      in the first place knowing we would use transposing and calculations. Result of x.T =>') 
print(x.T)
print(f'      and the dimensions are (2 x 1), shape: {x.T.shape}.')   
print("h)    No, mathematically the two dimensions do not match but in Numpy they can with help of broadcasting both to dim (2, 2)->")
print(x+x.T)
print(f'i)    {np.linalg.norm(x)}')

a)    Shape:(1, 2)  => dimension 1 x 2 (a row vector with 2 elements)
b)    [[20 15]]
c)    [[12  9]]
d)    [[32 24]]
e)    [[32 24]]
f)    [[12  9]]
g)    Since transposing a 1D row vector doesn't make any differense in Numpy I've chosen to write the array as an 2D array
      in the first place knowing we would use transposing and calculations. Result of x.T =>
[[4]
 [3]]
      and the dimensions are (2 x 1), shape: (2, 1).
h)    No, mathematically the two dimensions do not match but in Numpy they can with help of broadcasting both to dim (2, 2)->
[[8 7]
 [7 6]]
i)    5.0


In [145]:
# 10.1.2   
v = np.array([[3],
              [7],
              [0],
              [11]])    #column vector
print('a)')
print(f'{v.shape} => dimension 4 x 1 (vector with 4 rows with 1 column)')
print()
print('b)')
print(2*v)
print()  
print('c)')
print(5*v+2*v)
print()
print('d)')
print(4*v-2*v)
print()
print('e)')
print(f'{v.T} => dimension 1 x 4 (1 row with 4 columns)')
print()
print('f)')
print(np.linalg.norm(v))

a)
(4, 1) => dimension 4 x 1 (vector with 4 rows with 1 column)

b)
[[ 6]
 [14]
 [ 0]
 [22]]

c)
[[21]
 [49]
 [ 0]
 [77]]

d)
[[ 6]
 [14]
 [ 0]
 [22]]

e)
[[ 3  7  0 11]] => dimension 1 x 4 (1 row with 4 columns)

f)
13.379088160259652


In [146]:
# 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print('a)')
print(np.linalg.norm(v1))
print()
print('b)')
print(np.linalg.norm(v1-v2))

a)
7.14142842854285

b)
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [147]:
# 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

print('a)')
print(2 * A)
print('b)')
print(B - 2*A)
print('c)')
print(3*C - 2*E) # undefined, Numpy broadcast to get the output
print('d)')
print(2*D - 3*C)
print('e)')
print(D.T + 2*D)
print('f)')
print(2*C.T - 2*D.T)
print('g)')
print("Undefined. Broadcast won't work since both dimensions are incompatible shapes.")
print('h)')
print("Undefined. Broadcast won't work since both dimensions are incompatible shapes.")
print('i)')
print(C @ D)
print('j)')
print(C @ B)
print('k)')
print(C @ I)
print('l)')
print(A @ B.T)


a)
[[ 4  2 -2]
 [ 2 -2  2]]
b)
[[ 0 -4  3]
 [ 0 -2 -4]]
c)
[[ 1  4]
 [ 2 -1]]
d)
[[3 2]
 [2 3]]
e)
[[ 9 12]
 [12  9]]
f)
[[-4 -4]
 [-4 -4]]
g)
Undefined. Broadcast won't work since both dimensions are incompatible shapes.
h)
Undefined. Broadcast won't work since both dimensions are incompatible shapes.
i)
[[11 10]
 [10 11]]
j)
[[  8 -10  -3]
 [ 10  -8   0]]
k)
[[1 2]
 [2 1]]
l)
[[5 2]
 [7 4]]


In [148]:
# 10.2.2
A = np.array([[2, 3, 4], [5, 4, 1]])
print(A @ A.T)

[[29 26]
 [26 42]]


In [149]:
# 10.2.3
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(A @ B == A @ C)
print(B != C)    # If true B is not equal to C

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [150]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [151]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [152]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [153]:
# As described in comments above: v1 is a copy since there is no original array linked (None) as shown with v1.base
# v2 on the other hand is a view since v2.base show the original array
# If changes are made on v2 it will also affect v1 on the corresponding elements.